import { DashboardShell } from "@/components/dashboard-shell";
import { getAuthenticatedContext } from "@/lib/household";
import { acceptReconciliation, cancelOccurrence, cancelPayableSeries, createPayable, payOccurrence, rejectReconciliation, updateOccurrence } from "./actions";
import Link from "next/link";
import { detectRecurringTransactions } from "@/lib/finance/recurring";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" });
const today = new Date().toISOString().slice(0, 10);
const monthEnd = `${today.slice(0, 8)}${String(new Date(Number(today.slice(0, 4)), Number(today.slice(5, 7)), 0).getDate()).padStart(2, "0")}`;
type PageProps = { searchParams: Promise<{ error?: string; success?: string; view?: string; month?: string }> };

function relationName(value: { name: string; nickname?: string | null } | { name: string; nickname?: string | null }[] | null) {
  const item = Array.isArray(value) ? value[0] : value;
  return item?.nickname || item?.name;
}

function nextMonthlyDate(value: string) {
  const [year, month, day] = value.split("-").map(Number);
  const lastDay = new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
  return new Date(Date.UTC(year, month, Math.min(day, lastDay))).toISOString().slice(0, 10);
}

export default async function PayablesPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const selectedMonth = /^\d{4}-(0[1-9]|1[0-2])$/.test(params.month ?? "") ? params.month! : today.slice(0, 7);
  const [selectedYear, selectedMonthNumber] = selectedMonth.split("-").map(Number);
  const selectedStart = `${selectedMonth}-01`;
  const selectedEnd = new Date(Date.UTC(selectedYear, selectedMonthNumber, 1)).toISOString().slice(0, 10);
  const previousMonth = new Date(Date.UTC(selectedYear, selectedMonthNumber - 2, 1)).toISOString().slice(0, 7);
  const nextMonth = new Date(Date.UTC(selectedYear, selectedMonthNumber, 1)).toISOString().slice(0, 7);
  const selectedMonthLabel = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${selectedStart}T12:00:00Z`));
  const { supabase, membership } = await getAuthenticatedContext();
  const householdId = membership?.household_id;
  const recurringSince = new Date(); recurringSince.setUTCDate(recurringSince.getUTCDate() - 190);
  const [occurrencesResult, accountsResult, categoriesResult, cardInstallmentsResult, suggestionsResult, recurringTransactionsResult] = householdId ? await Promise.all([
    supabase.from("payable_occurrences").select("id, due_on, amount_cents, occurrence_number, status, paid_on, payables(id, title, schedule_type, occurrence_count, notes, accounts(name, nickname), categories(name))").eq("household_id", householdId).order("due_on").limit(300),
    supabase.from("accounts").select("id, name, nickname").eq("household_id", householdId).eq("is_active", true).order("name"),
    supabase.from("categories").select("id, name").eq("household_id", householdId).eq("kind", "expense").eq("is_active", true).order("name"),
    supabase.from("transactions").select("id, description, amount_cents, occurred_on, installment_number, installment_count, credit_cards(name, nickname), categories(name)").eq("household_id", householdId).eq("type", "expense").eq("status", "confirmed").not("credit_card_id", "is", null).gt("installment_count", 1).gte("occurred_on", today).order("occurred_on").limit(100),
    supabase.from("payable_reconciliation_suggestions").select("id, score, reason, payable_occurrences(due_on, amount_cents, payables(title, accounts(name, nickname))), transactions(description, amount_cents, occurred_on)").eq("household_id", householdId).eq("status", "pending").order("score", { ascending: false }).limit(20),
    supabase.from("transactions").select("id, description, amount_cents, occurred_on, account_id, categories(name)").eq("household_id", householdId).eq("type", "expense").eq("status", "confirmed").not("account_id", "is", null).gte("occurred_on", recurringSince.toISOString().slice(0, 10)).order("occurred_on").limit(2500),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }, { data: [] }];
  const allOccurrences = occurrencesResult.data ?? [];
  const monthOccurrences = allOccurrences.filter((item) => item.due_on >= selectedStart && item.due_on < selectedEnd);
  const visibleOccurrences = params.view === "all" ? monthOccurrences : monthOccurrences.filter((item) => item.status === "pending");
  const pending = allOccurrences.filter((item) => item.status === "pending");
  const overdue = pending.filter((item) => item.due_on < today);
  const dueThisMonth = pending.filter((item) => item.due_on >= today && item.due_on <= monthEnd);
  const nextSeven = new Date(`${today}T12:00:00`); nextSeven.setDate(nextSeven.getDate() + 7);
  const nextSevenIso = nextSeven.toISOString().slice(0, 10);
  const dueSoon = pending.filter((item) => item.due_on >= today && item.due_on <= nextSevenIso);
  const firstWeekday = new Date(`${selectedStart}T12:00:00`).getDay();
  const daysInSelectedMonth = new Date(selectedYear, selectedMonthNumber, 0).getDate();
  const calendarDays = [...Array.from({ length: firstWeekday }, () => null), ...Array.from({ length: daysInSelectedMonth }, (_, index) => index + 1)];
  const existingPayableNames = new Set(allOccurrences.map((item) => { const payable = Array.isArray(item.payables) ? item.payables[0] : item.payables; return payable?.title.trim().toLocaleLowerCase("pt-BR"); }).filter(Boolean));
  const recurringSuggestions = detectRecurringTransactions((recurringTransactionsResult.data ?? []).map((row) => ({ id: row.id, description: row.description, amount_cents: row.amount_cents, occurred_on: row.occurred_on, category: relationName(row.categories) || "Sem categoria", sourceId: row.account_id || "unknown" })))
    .filter((item) => item.cadence === "monthly" && item.sourceId !== "unknown" && nextMonthlyDate(item.lastDate) >= today && !existingPayableNames.has(item.description.trim().toLocaleLowerCase("pt-BR"))).slice(0, 5);

  return <DashboardShell active="payables"><section className="content settings-content payables-content">
    <header><div><p className="eyebrow">AGENDA FINANCEIRA</p><h1>Contas a pagar</h1><p className="muted">Veja o que vem pela frente sem misturar previsão com gasto realizado.</p></div></header>
    {params.error && <p className="form-message error">{params.error}</p>}{params.success && <p className="form-message success">{params.success}</p>}
    {!!suggestionsResult.data?.length && <section className="reconciliation-section"><div className="section-heading"><div><p className="eyebrow">CONCILIAÇÃO ASSISTIDA</p><h2>Já foi paga?</h2></div><span className="count-badge">{suggestionsResult.data.length}</span></div><p className="muted">Encontramos movimentações parecidas. Confirme apenas quando forem o mesmo pagamento.</p><div className="reconciliation-list">{suggestionsResult.data.map((suggestion) => { const occurrence = Array.isArray(suggestion.payable_occurrences) ? suggestion.payable_occurrences[0] : suggestion.payable_occurrences; const transaction = Array.isArray(suggestion.transactions) ? suggestion.transactions[0] : suggestion.transactions; const payable = Array.isArray(occurrence?.payables) ? occurrence.payables[0] : occurrence?.payables; return <article className="card reconciliation-item" key={suggestion.id}><div className="reconciliation-score"><strong>{suggestion.score}%</strong><span>compatível</span></div><div><strong>{payable?.title}</strong><small>Previsto: {money.format((occurrence?.amount_cents ?? 0) / 100)} em {occurrence?.due_on ? date.format(new Date(`${occurrence.due_on}T12:00:00`)) : "—"}</small><span>↕</span><strong>{transaction?.description}</strong><small>Encontrado: {money.format((transaction?.amount_cents ?? 0) / 100)} em {transaction?.occurred_on ? date.format(new Date(`${transaction.occurred_on}T12:00:00`)) : "—"} · {relationName(payable?.accounts ?? null)}</small><p>{suggestion.reason}</p></div><div className="reconciliation-actions"><form action={acceptReconciliation}><input type="hidden" name="suggestion_id" value={suggestion.id} /><button type="submit">É o mesmo pagamento</button></form><form action={rejectReconciliation}><input type="hidden" name="suggestion_id" value={suggestion.id} /><button className="quiet-danger" type="submit">Não é</button></form></div></article>; })}</div></section>}
    {!!recurringSuggestions.length && <details className="card recurring-payable-suggestions"><summary><span>↻</span><div><strong>Transformar padrões em contas agendadas</strong><small>{recurringSuggestions.length} sugestões encontradas no histórico bancário</small></div></summary><div>{recurringSuggestions.map((item) => <article key={item.id}><div><strong>{item.description}</strong><small>{item.category} · {item.confidence}% de confiança · última em {date.format(new Date(`${item.lastDate}T12:00:00`))}</small></div><strong>{money.format(item.monthlyCents / 100)}/mês</strong><form action={createPayable}><input type="hidden" name="title" value={item.description} /><input type="hidden" name="schedule_type" value="recurring" /><input type="hidden" name="account_id" value={item.sourceId} /><input type="hidden" name="amount" value={(item.monthlyCents / 100).toFixed(2).replace(".", ",")} /><input type="hidden" name="first_due_on" value={nextMonthlyDate(item.lastDate)} /><input type="hidden" name="occurrence_count" value="12" /><input type="hidden" name="auto_renew" value="on" /><input type="hidden" name="notes" value="Criada a partir de um padrão recorrente identificado pelo Poupemos." /><button type="submit">Adicionar à agenda</button></form></article>)}</div></details>}
    <section className="payables-summary"><article><span>A vencer neste mês</span><strong>{money.format(dueThisMonth.reduce((sum, item) => sum + item.amount_cents, 0) / 100)}</strong></article><article><span>Próximos 7 dias</span><strong>{dueSoon.length}</strong><small>{money.format(dueSoon.reduce((sum, item) => sum + item.amount_cents, 0) / 100)}</small></article><article className={overdue.length ? "overdue" : ""}><span>Em atraso</span><strong>{overdue.length}</strong><small>{money.format(overdue.reduce((sum, item) => sum + item.amount_cents, 0) / 100)}</small></article></section>
    <details className="card payable-create"><summary>+ Adicionar conta ou parcelamento</summary><form action={createPayable}><div className="payable-form-row"><label>Descrição<input name="title" maxLength={120} placeholder="Ex.: Condomínio" required /></label><label>Categoria<select name="category_id"><option value="">Sem categoria</option>{categoriesResult.data?.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><div className="payable-form-row"><label>Tipo<select name="schedule_type" defaultValue="one_time"><option value="one_time">Conta única</option><option value="installment">Parcelamento</option><option value="recurring">Conta recorrente</option></select></label><label>Conta para pagamento<select name="account_id" required><option value="">Selecione</option>{accountsResult.data?.map((account) => <option key={account.id} value={account.id}>{account.nickname || account.name}</option>)}</select></label></div><div className="payable-form-row three"><label>Valor<input name="amount" inputMode="decimal" placeholder="250,00" required /><small>No parcelamento, informe o valor total.</small></label><label>Primeiro vencimento<input name="first_due_on" type="date" required /></label><label>Quantidade<input name="occurrence_count" type="number" min={1} max={60} defaultValue={1} /><small>Meses ou parcelas.</small></label></div><label className="checkbox-label payable-renew"><input name="auto_renew" type="checkbox" />Manter sempre 12 meses futuros <small>Usado somente para contas recorrentes.</small></label><label>Observação<input name="notes" maxLength={300} placeholder="Opcional" /></label><button type="submit">Adicionar à agenda</button></form></details>
    <section className="payables-calendar"><header><Link aria-label="Mês anterior" href={`/dashboard/contas-a-pagar?month=${previousMonth}`}>←</Link><div><p className="eyebrow">CALENDÁRIO</p><h2>{selectedMonthLabel}</h2></div><Link aria-label="Próximo mês" href={`/dashboard/contas-a-pagar?month=${nextMonth}`}>→</Link></header><div className="calendar-weekdays">{["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((weekday) => <span key={weekday}>{weekday}</span>)}</div><div className="calendar-grid">{calendarDays.map((day, index) => { if (!day) return <span className="calendar-day empty" key={`empty-${index}`} />; const dayDate = `${selectedMonth}-${String(day).padStart(2, "0")}`; const scheduled = monthOccurrences.filter((item) => item.due_on === dayDate); const cards = cardInstallmentsResult.data?.filter((item) => item.occurred_on === dayDate) ?? []; return <article className={`calendar-day ${dayDate === today ? "today" : ""}`} key={dayDate}><strong>{day}</strong><div>{scheduled.slice(0, 2).map((item) => { const payable = Array.isArray(item.payables) ? item.payables[0] : item.payables; return <span className={item.status} key={item.id}>{payable?.title}<small>{money.format(item.amount_cents / 100)}</small></span>; })}{cards.slice(0, Math.max(0, 2 - scheduled.length)).map((item) => <span className="card-event" key={item.id}>{item.description}<small>{money.format(item.amount_cents / 100)}</small></span>)}{scheduled.length + cards.length > 2 && <small className="calendar-more">+{scheduled.length + cards.length - 2}</small>}</div></article>; })}</div><div className="calendar-legend"><span><i className="pending" />Conta agendada</span><span><i className="paid" />Paga</span><span><i className="card-event" />Cartão</span></div></section>
    <div className="payables-heading"><div><h2>Agenda de {selectedMonthLabel}</h2><span className="count-badge">{visibleOccurrences.length}</span></div><nav aria-label="Visualização da agenda"><Link className={params.view !== "all" ? "active" : ""} href={`/dashboard/contas-a-pagar?month=${selectedMonth}`}>Pendentes</Link><Link className={params.view === "all" ? "active" : ""} href={`/dashboard/contas-a-pagar?month=${selectedMonth}&view=all`}>Todas</Link></nav></div>
    {!visibleOccurrences.length && <article className="card empty-state"><span>✓</span><h2>Nada pendente</h2><p className="muted">Adicione uma conta para começar a organizar os próximos vencimentos.</p></article>}
    <section className="payables-list">{visibleOccurrences.map((occurrence) => { const payable = Array.isArray(occurrence.payables) ? occurrence.payables[0] : occurrence.payables; const isOverdue = occurrence.status === "pending" && occurrence.due_on < today; return <article className={`card payable-item ${occurrence.status} ${isOverdue ? "overdue" : ""}`} key={occurrence.id}><time dateTime={occurrence.due_on}><strong>{occurrence.due_on.slice(8, 10)}</strong><span>{date.format(new Date(`${occurrence.due_on}T12:00:00`)).split(" de ")[1] ?? occurrence.due_on.slice(5, 7)}</span></time><div className="payable-main"><div><strong>{payable?.title}</strong>{(payable?.occurrence_count ?? 0) > 1 && <span>{occurrence.occurrence_number}/{payable?.occurrence_count}</span>}</div><small>{relationName(payable?.categories ?? null) || "Sem categoria"} · {relationName(payable?.accounts ?? null) || "Conta"}</small></div><div className="payable-value"><strong>{money.format(occurrence.amount_cents / 100)}</strong><span>{occurrence.status === "paid" ? `Pago em ${date.format(new Date(`${occurrence.paid_on}T12:00:00`))}` : occurrence.status === "cancelled" ? "Cancelada" : isOverdue ? "Em atraso" : "Pendente"}</span></div>{occurrence.status === "pending" && <div className="payable-actions"><details><summary>Marcar como paga</summary><form action={payOccurrence}><input type="hidden" name="occurrence_id" value={occurrence.id} /><label>Data do pagamento<input name="paid_on" type="date" defaultValue={today} required /></label><button type="submit">Confirmar pagamento</button></form></details><details className="payable-edit"><summary>Editar</summary><form action={updateOccurrence}><input type="hidden" name="occurrence_id" value={occurrence.id} /><label>Valor<input name="amount" inputMode="decimal" defaultValue={(occurrence.amount_cents / 100).toFixed(2).replace(".", ",")} required /></label><label>Vencimento<input name="due_on" type="date" defaultValue={occurrence.due_on} required /></label><button type="submit">Salvar</button></form></details><form action={cancelOccurrence}><input type="hidden" name="occurrence_id" value={occurrence.id} /><button className="quiet-danger" type="submit">Cancelar</button></form>{(payable?.occurrence_count ?? 0) > 1 && <details className="payable-series-cancel"><summary>Cancelar série</summary><form action={cancelPayableSeries}><input type="hidden" name="payable_id" value={payable?.id} /><label>Digite CANCELAR<input name="confirmation" autoComplete="off" required /></label><button className="quiet-danger" type="submit">Cancelar parcelas futuras</button></form></details>}</div>}</article>; })}</section>
    {!!cardInstallmentsResult.data?.length && <section className="card-payables"><div className="section-heading"><div><p className="eyebrow">JÁ REGISTRADO</p><h2>Próximas parcelas dos cartões</h2></div><span className="count-badge">{cardInstallmentsResult.data.length}</span></div><p className="muted">Estes valores já estão nas transações e faturas. Aqui aparecem apenas como agenda.</p><div>{cardInstallmentsResult.data.map((item) => <article key={item.id}><time>{date.format(new Date(`${item.occurred_on}T12:00:00`))}</time><div><strong>{item.description}</strong><small>{relationName(item.credit_cards)} · {relationName(item.categories) || "Sem categoria"}{item.installment_count > 1 ? ` · ${item.installment_number}/${item.installment_count}` : ""}</small></div><strong>{money.format(item.amount_cents / 100)}</strong></article>)}</div></section>}
  </section></DashboardShell>;
}
